{
  "redes" :[
    {
        "link":"https://www.facebook.com/fundasoft.cordoba",
	      "icono":"bi-facebook"
    },
    {
        "link":"https://www.instagram.com/fundasoft.cordoba",
        "icono":"bi-instagram"
    },
    {
        "link":"https://www.youtube.com/c/FundasoftC%C3%B3rdoba/featured",
        "icono":"bi-youtube"
    },
    {
        "link":"https://www.linkedin.com/in/fundasoft/",
        "icono":"bi-linkedin"
    },
    {
        "link":"https://github.com/Fundasoft",
        "icono":"bi-github"
    }
  ],
  "nombre":"Fundasoft",
  "anio":"2020",
  "telefono": "+54 9 3515 15-7777"
}
