{
  "value": [
    {
      "icon": "hdd",
      "title": "drive",
      "description": "Recursos compartidos",
      "link": ""
    },
    {
      "icon": "whatsapp",
      "title": "whatsapp",
      "description": "Grupo compartido",
      "link": ""
    },
    {
      "icon": "graph-up-arrow",
      "title": "Analitycs",
      "description": "Estadisticas externas",
      "link": ""
    }
  ],
  "Y": 4,
  "UUID": "7e9f0a281a6f3f830b32156eac377e7306ccc7719039370803325c41610a2163"
}